const { withAppBuildGradle } = require('expo/config-plugins');

const marker = '// Codenotch upload signing (generated by withReleaseSigning)';

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning requires a Groovy app/build.gradle');
    }

    let contents = config.modResults.contents;
    if (contents.includes(marker)) return config;

    // Fail visibly if a future Expo template changes these insertion points.
    const androidBlock = /^android \{/m;
    const signingBlock = /^    signingConfigs \{/m;
    const releaseSigning = /^(        release \{\n)(?:            \/\/[^\n]*\n)*            signingConfig signingConfigs\.debug$/m;
    for (const anchor of [androidBlock, signingBlock, releaseSigning]) {
      if ((contents.match(new RegExp(anchor.source, 'gm')) || []).length !== 1) {
        throw new Error('withReleaseSigning: unexpected Expo Android signing template');
      }
    }

    contents = contents.replace(androidBlock, `${marker}
def codenotchUploadProperties = [
    'CODENOTCH_UPLOAD_STORE_FILE',
    'CODENOTCH_UPLOAD_STORE_PASSWORD',
    'CODENOTCH_UPLOAD_KEY_ALIAS',
    'CODENOTCH_UPLOAD_KEY_PASSWORD'
]
def codenotchHasUploadSigning = codenotchUploadProperties.every {
    def value = project.findProperty(it)
    value != null && !value.toString().trim().isEmpty()
}

android {`);
    contents = contents.replace(signingBlock, `    signingConfigs {
        if (codenotchHasUploadSigning) {
            upload {
                storeFile file(project.property('CODENOTCH_UPLOAD_STORE_FILE'))
                storePassword project.property('CODENOTCH_UPLOAD_STORE_PASSWORD')
                keyAlias project.property('CODENOTCH_UPLOAD_KEY_ALIAS')
                keyPassword project.property('CODENOTCH_UPLOAD_KEY_PASSWORD')
            }
        }`);
    contents = contents.replace(releaseSigning, `$1            // Missing upload properties keep local release builds usable.
            signingConfig codenotchHasUploadSigning ? signingConfigs.upload : signingConfigs.debug`);

    config.modResults.contents = contents;
    return config;
  });
};
